#!/bin/zsh

. ~/.zsh/vars

alias mv='mv -v'
alias mmv='noglob zmv -W'
alias rm='rm -v'
alias cp='cp -v'
alias wget='wget --timeout 10'
alias grep='grep --color=auto'
alias c='clear'
alias ll='ls -ahl | more; echo "\e[1;32m --[\e[1;34m Dirs:\e[1;36m `ls -al | egrep \"^drw\" | wc -l` \e[1;32m|\e[1;35m Files: \e[1;31m`ls -al | egrep -v \"^drw\" | grep -v total | wc -l` \e[1;32m]--"'
alias cdc='cd; clear'
alias ls='ls -GF'
alias ccat='pygmentize -g'

alias vim='emacsclient -a "" -t'
alias svndiff='svn diff $* | colordiff | lv -c'
alias vgaon='xrandr --output VGA1 --auto --right-of LVDS1'
alias vgaoff='xrandr --output VGA1 --off'
alias ctl='sudo systemctl'
alias halt='sudo poweroff'
alias reboot='sudo reboot'

alias vpnup='sudo systemctl start openvpn@client'
alias vpndown='sudo systemctl stop openvpn@client'
alias managerup='VBoxHeadless -s "Lastline Manager" &> ~/.vbox_ll_logs &'
alias manager_connect='ssh root@manager'
alias devwatch='docker exec -it website-user grunt watch'
alias devmount='sshfs -o allow_other,uid=$(id -u),gid=$(id -g) root@manager:/var/www/dev_website_user'

# Global aliases
alias -g L='| pygmentize -g | less -r'
alias -g BG='& exit'
alias -g C='|wc -l'
alias -g G='|grep'
alias -g H='|head'
alias -g Hl=' --help |& less -r'
alias -g LL='|& less -r'
alias -g N='&>/dev/null'
alias -g V='| vim -'

TF_ALIAS=fuck alias fuck='eval $(thefuck $(fc -ln -1 | tail -n 1)); fc -R'
